require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update